// Shared project data for Agora Hub
window.AgoraProjects = [
  {
    slug: "fiqhnafs",
    name: " مجالس فقه النفس - د. عبد الرحمان ذاكر الهاشمي",
    tagline: "سلسلة مجالس علمية في فقه النفس وتزكيتها وفق منهج الوحي",
    description: "مكتبة حية في الفقه، مقرونة بعمل تأملي على النفس. تعلّم الحكم، ثم تجسّده.",
    tags: ["Next.js", "MDX", "Postgres"],
    accent: "emerald",
    year: "2024",
    status: "منشور",
    glyph: "ف",
    glyphName: "فاء",
    href: "https://fiqhnafs.app",
  },
  {
    slug: "tadabbur",
    name: "تَدَبَّر",
    tagline: "أداةٌ لتدبّر القرآن الكريم",
    description: "فضاء للدراسة لمتابعة دروسي وقراءاتي وملاحظاتي وأرشفتها ومشاركتها — مصمَّم كمجلس رقمي.",
    tags: ["Next.js", "Tailwind", "tRPC"],
    accent: "gold",
    year: "2024",
    status: "منشور",
    glyph: "ع",
    glyphName: "عين",
    href: "https://tadabbur.app",
  },
  {
    slug: "tafsir",
    name: "صفوة التفاسير",
    tagline: "أمهات كتب التفسير ",
    description: "قراءة آية بآية مع تفاسير الأئمة، والبحث الدلالي عربي-فرنسي، والإشارات المرجعية الدائمة.",
    tags: ["Next.js", "Edge", "Vector DB"],
    accent: "emerald",
    year: "2024",
    status: "منشور",
    glyph: "ت",
    glyphName: "تاء",
    href: "https://tafsir.app",
  },
    {
    slug: "fikr",
    name: "رحيق المعرفة",
    tagline: " دوراتك العلميّة",
    description: "",
    tags: ["Next.js", "MDX"],
    accent: "gold",
    year: "2023",
    status: "منشور",
    glyph: "ك",
    glyphName: "كاف",
    href: "#",
  },
  {
    slug: "hikam",
    name: "حكم",
    tagline: "عٌدَّة المريد ",
    description: "أداة خفيفة خالية من الإعلانات، تحسب الصلوات الخمس بحسب موقعك والمنهج الذي تختاره.",
    tags: ["SvelteKit", "PWA"],
    accent: "gold",
    year: "2025",
    status: "تجريبي",
    glyph: "م",
    glyphName: "ميم",
    href: "#",
  },
  {
    slug: "sirah",
    name: "Sīrah",
    tagline: "الخط الزمني التفاعلي للسيرة النبوية",
    description: "شريط زمني عمودي لأحداث حياة النبي ﷺ، مرتبطة بالآيات والأحاديث المناظرة.",
    tags: ["Astro", "D3"],
    accent: "emerald",
    year: "2025",
    status: "تجريبي",
    glyph: "س",
    glyphName: "سين",
    href: "#",
  },
  {
    slug: "isnad",
    name: "Isnād",
    tagline: "مُصوِّر سلاسل الإسناد",
    description: "رسم بياني تفاعلي لأسانيد الكتب الحديثية الكبرى — لترى في لمحة واحدة من يروي عمّن.",
    tags: ["React", "D3", "Postgres"],
    accent: "emerald",
    year: "2025",
    status: "نموذج أولي",
    glyph: "إ",
    glyphName: "إسناد",
    href: "#",
  },
  {
    slug: "duroos",
    name: "Durūs",
    tagline: "دروس صوتية مصنَّفة ومفهرسة",
    description: "مكتبة من الدروس الصوتية مع النص المكتوب والبحث الشامل والإشارات الزمنية.",
    tags: ["Next.js", "Whisper"],
    accent: "gold",
    year: "2024",
    status: "منشور",
    glyph: "د",
    glyphName: "دال",
    href: "#",
  },
  {
    slug: "maktabah",
    name: "Maktabah",
    tagline: "مكتبتي الشخصية المفتوحة",
    description: "فهرس قراءاتي في التراث والمعاصرة، مع اقتباسات مفهرسة وروابط بين الكتب.",
    tags: ["SvelteKit", "SQLite"],
    accent: "emerald",
    year: "2023",
    status: "منشور",
    glyph: "ب",
    glyphName: "باء",
    href: "#",
  },
];

// Detail content for the project page (FiqhNafs as the showcase)
window.AgoraProjectDetail = {
  slug: "fiqhnafs",
  name: "FiqhNafs",
  arabic: "فقه النفس",
  tagline: "الفقه الإسلامي وتزكية النفس",
  hero: "تعلّم الحكم، ثم تجسّده. يجمع FiqhNafs دليلاً فقهياً منظَّماً وسجلاً للعمل الداخلي، ليتنامى العلم والخلق معاً.",
  year: "2024",
  status: "منشور — v2.3",
  role: "تصميم، تطوير، تحرير",
  url: "https://fiqhnafs.app",
  github: "https://github.com/example/fiqhnafs",
  tags: ["Next.js 16", "Tailwind v4", "Postgres", "MDX", "Stripe", "i18n"],
  features: [
    {
      title: "دليل منظَّم",
      body: "أكثر من 200 فصل محرَّر بـ MDX، مرتَّبة حسب المذهب الفقهي، مع إحالات إلى الأدلة النصية.",
    },
    {
      title: "مفكرة النفس",
      body: "دفتر يومي موجَّه: نيات الصباح، ومحاسبة المساء، ومتابعة العادات الروحية على المدى.",
    },
    {
      title: "بحث ثنائي اللغة",
      body: "فهرس دلالي عربي-فرنسي يجد المصطلح التقني حتى إن كُتب بغير لغة الاستعلام.",
    },
    {
      title: "وضع بلا إنترنت",
      body: "تطبيق ويب تقدمي كامل: المحتوى متاح والمفكرة تعمل دون اتصال بالشبكة.",
    },
  ],
  stack: ["Next.js 16", "Tailwind CSS v4", "shadcn/ui", "Postgres + Drizzle", "MDX", "next-intl"],
};
